---
{{- with .Values.AWX }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-admin-password
  namespace: {{ $.Release.Namespace }}
stringData:
  password: {{ .spec.admin_password_secret }}
{{- end }}